### PR TITLE
add Yoruba diacritics

### PR DESCRIPTION
**Pull request by BenAji**
I added the common diacritics to the json file

### CODE REVIEW

**Comment by chrisemezue** [comment]
Thank you so much @BenAji 
And sorry for the late reply.
Besides the diacritics are there some non-Latin alphabets of Yoruba?
For example, it says [here](https://en.wikipedia.org/wiki/Yoruba_alphabet)
> The Beninese alphabet has the letters Ɛ and Ɔ, and previously had C.

**Comment by BenAji** [comment]
Yes that's right, these are represented with undertone.

**Comment by chrisemezue** [comment]
> Yes that's right, these are represented with undertone.

I am not sure I understand. Please can you explain?

**Comment by BenAji** [comment]
The Benin version is a bit different from the Nigerian yoruba , I will encourage you should get more details here for clarity
https://omniglot.com/writing/yoruba.htm

**Comment by chrisemezue** [comment]
Okay, thank you. I have gone through what you sent.
My question remains: the alphabet of the Benin version, should it or should it not be added to our rules? 

If it should then those Benin alphabets should be added before merging.

If the answer is No, then I'll go ahead and merge the pull request right away.

**Comment by BenAji** [comment]
No, the Benin Alphabets are not part of the main Yoruba Alphabet.

**Pull request merged**
